### ISSUE TITLE
Polygon's 1.0 Roadmap

### ISSUE THREAD

**Issue by thesobercoder** [thesobercoder/polygon#1]
This issue tracks the v1.0 plans for Polygon.

## Layouts

- [ ] Left Half
- [ ] Right Half
- [ ] Top Half
- [ ] Bottom Half
- [ ] First Two Thirds
- [ ] Last Two Thirds
- [ ] Top Left
- [ ] Top Right
- [ ] Bottom Left
- [ ] Bottom Right
- [ ] First Fourth
- [ ] Second Fourth
- [ ] Third Fourth
- [ ] Last Fourth
- [ ] Next Display
- [ ] Previous Display

## DevOps
- [ ] Implement automated release via tagging
- [ ] Implement automated release notes via tagging

## Release
- [ ] Produce from tag zipped binary for distribution
- [ ] Produce from tag installer for distribution
- [ ] Produce SHA256 hashes for both distribution types
